---
title: "git_00"
author: "Caitlyn Hense"
date: "2/10/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
How doth the little crocodile   
  Improve his shining tail,   
  And pour the waters of the Nile  
  On every golden scale!  
  How cheerfully he seems to grin,  
  
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Something there is that doesn’t love a wall,  
That sends the frozen-ground-swell under it,  
And spills the upper boulders in the sun;  
And makes gaps even two can pass abreast.  
The work of hunters is another thing:

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The moon was shining sulkily,  
   Because she thought the sun  
   
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
 HEAR the sledges with the bells --  
 Silver bells !  
 What a world of merriment their melody foretells !  
     How they tinkle, tinkle, tinkle,  
      In the icy air of night !  
      While the stars that oversprinkle  
      All the heavens, seem to twinkle  
      With a crystalline delight ;  
      Keeping time, time, time,  
      In a sort of Runic rhyme,